name: Spring Boot CI

on:
  push:
      branches: ["master"]
  pull_request:
      branches: ["master"]

jobs:
    build:
      runs-on: windows latest
       steps:
       - name: Checkout source
         uses: action/checkout@v3

       - name: Set up JDK 17
         uses: action/setup-java@v3
         with:
            java-version: "17"
            distribution: "temurin"

       - name: Build with maven
         run: mvn clean install

       
